#!/bin/bash
# Multi-Agent Badminton Scheduler - Quick Start Script

echo "🏸 Multi-Agent Badminton Scheduler"
echo "=================================="
echo ""
echo "This system requires 3 separate terminals to run 3 agents."
echo ""
echo "📋 Instructions:"
echo ""
echo "1. Open 3 SEPARATE terminals (Press Ctrl+Alt+T three times)"
echo ""
echo "2. In Terminal 1, run:"
echo "   cd /home/jayant/genAICourse/multi-agent-collaboration"
echo "   source multiagent/bin/activate"
echo "   python agents/bean/bean_agent.py"
echo ""
echo "3. In Terminal 2, run:"
echo "   cd /home/jayant/genAICourse/multi-agent-collaboration"
echo "   source multiagent/bin/activate"
echo "   python agents/joy/joy_agent.py"
echo ""
echo "4. In Terminal 3, run:"
echo "   cd /home/jayant/genAICourse/multi-agent-collaboration"
echo "   source multiagent/bin/activate"
echo "   python agents/organizer/organizer_agent.py"
echo ""
echo "5. Once all 3 agents are running, test with:"
echo "   curl -s http://localhost:8003/health | python -m json.tool"
echo ""
echo "6. Schedule badminton match:"
echo "   curl -X POST http://localhost:8003/schedule_badminton -H 'Content-Type: application/json' -d '{\"duration_hours\": 2}'"
echo ""
echo "📚 For detailed instructions, see:"
echo "   - TESTING_GUIDE.md (curl commands)"
echo "   - QUICK_START.md (5-minute guide)"
echo "   - EXECUTION_GUIDE.md (complete guide)"
echo ""
echo "✅ Dependencies are already installed!"
echo "✅ API key is already configured!"
echo ""
echo "Press any key to continue..."
read -n 1
